<div class="container-fluid">    
    <div class=" col-md-4 ">                   
        <div class="panel panel-success" >
            <div class="panel-heading">
                <div class="panel-title">
                    <h4 style="text-align: center; color:#921B46 ">
                         <span class="glyphicon glyphicon-user"></span>
                        <b>Acesso Restrito</b>
                    </h4>
                </div>
            </div>     
            <div style="padding-top:30px" class="panel-body" >
                <div style="display:none" id="login-alert" class="alert alert-danger col-sm-12"></div>
                    <?php echo $this->form; ?>
            </div>                     
        </div>  
    </div>    
</div>




